#define DOUBLEWHOLE 8.0
#define WHOLE 4.0
#define HALF 2.0
#define QUARTER 1.0
#define EIGHTH 0.5
#define SIXTEENTH 0.25
#define THIRTYSECOND 0.125
#define SIXTYFOURTH 0.0625

#define DOUBLEWHOLE_DOT DOUBLEWHOLE * 1.5
#define WHOLE_DOT WHOLE * 1.5
#define HALF_DOT HALF * 1.5
#define QUARTER_DOT QUARTER * 1.5
#define EIGHTH_DOT EIGHTH * 1.5
#define SIXTEENTH_DOT SIXTEENTH * 1.5
#define THIRTYSECOND_DOT THIRTYSECOND * 1.5
#define SIXTYFOURTH_DOT SIXTYFOURTH * 1.5
